### ISSUE TITLE
scrolling on mobile (in app browser facebook messenger) only works after clicking page dot

### ISSUE THREAD

**Issue by LionBeach** [prjct-samwest/docSlider#2]
Hi,

Great project!
I noticed that scrolling on mobile doesn't work when you land on the page. After you pushed one of the pagedots it works.

Tested on Android Pixel 3a and ios iPhone 8

**Comment by prjct-samwest** [comment]
Hello.
Thank you for the report.

I tested the demo page in the facebook messenger app browser on iPhone 8 and it seems to work fine in my environment.
https://prjct-samwest.github.io/docSlider/

Can you provide specific details, if possible?
Unresponsive, conflicting with other actions, etc.

**Comment by LionBeach** [comment]
Hi,

I tested some more. On iphone your page works indeed. I had some problems with a codepen but this is most likely a codepen thing and not worth investigating.

On android the problem is definetly there. I made a video of this. You can see that it doesn't work until the moment I double tap. Or if i were to press an id link or a pagedot.

I've also tested a simple site with javascript that looks like this:

`docSlider.init({
  speed: 400
});
docSlider.jumpPage(1);`

On a desktop and chrome for android the page scroll to the second section when it is loaded. In facebook messenger in app browser it doesn't.

Hope this helps!

[video-1591345832.zip](https://github.com/prjct-samwest/docSlider/files/4734993/video-1591345832.zip)

**Comment by prjct-samwest** [comment]
Hi, thanks for the detailed report.
The video was very helpful.

It has helped me to determine the cause of the problem.
- - -
Can you try the following?

docSlider.js:Line 191 - Remove the focusout event.
https://github.com/prjct-samwest/docSlider/blob/20ba0a870aba4b6e35608ef52a77a50d4d2341aa/docSlider.js#L191
In some mobile browsers, focusout causes focus to be disabled and It seems to be issues.
This process was originally created as an anti-focus solution for desktop chrome browsers, however, the logic has now been changed and it is safe to remove it.
- - -

Thank you again for your time.
I hope that this problem is resolved quickly.

**Comment by LionBeach** [comment]
Hi,

Thanks for getting back!
I commented out line 191, but it doesn't solve the issue.

While doing this I noticed the the zip you provide at [https://github.com/prjct-samwest/docSlider/archive/v2.0.1.zip](https://github.com/prjct-samwest/docSlider/archive/v2.0.1.zip) contains v1.0.0 instead of v2.0.1

I mention this because when my test site was accidentally running on v1.0.0 the problem concerning "docSlider.jumpPage(1);" at the start, was solved! When I'm running v2.0.1 the page didn't autoscroll when it loaded.

The other problem was the same between v1.0.0, v2.0.1 and adjusted v2.0.1

Greetings

**Comment by prjct-samwest** [comment]
Hi, thank you very much for your kind support every time.

Uploaded a modified js file to the develop branch as version v2.0.4 I did.
https://github.com/prjct-samwest/docSlider/blob/develop/docSlider.js

Please check it out..

- - -
Oops, my apologies. I've re-uploaded it.
> the zip you provide at https://github.com/prjct-samwest/docSlider/archive/v2.0.1.zip contains v1.0.0 instead of v2.0.1

**Comment by LionBeach** [comment]
Hi,

It works! Both issues have been solved on android facebook messenger in-app browser!
Thank you so much!

I will test in a few hours on iphone, as i don't have one nearby, to confirm and than close the issue.

Greetings!

**Comment by prjct-samwest** [comment]
Hi, thanks for the check.

I'm glad we were able to resolve the issue.
Thank you so much.

**Comment by LionBeach** [comment]
iPhone also works fine!

Thanks again!
